"use client";
import { LazyImage } from "@/componets/RandomFox";
import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import type { MouseEventHandler } from "react";
import { random } from "lodash";
const randomNum = () => random(1, 123);
const generateId = () => Math.random().toString(36).replace(".", "");

const Home: NextPage = () => {
  const [images, setImages] = useState<IFoxItems[]>([]);

  const addNewFox: MouseEventHandler<HTMLButtonElement> = (event): void => {
    event.preventDefault();
    setImages([
      ...images,
      {
        id: generateId(),
        url: `https://randomfox.ca/images/${randomNum()}.jpg`,
      },
    ]);
    window.plausible("addFox");
  };
  const deleteFox: MouseEventHandler<HTMLButtonElement> = (event): void => {
    event.preventDefault();
    setImages((prevArray) => prevArray.slice(0, -1));
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./favicon.ico" />
        <script
          defer
          data-domain="yourdomain.com"
          src="https://plausible.io/js/script.js"
        ></script>
      </Head>

      <main className="grid p-3 place-content-center">
        <h1 className="mb-2 text-3xl font-bold underline dark:text-white">
          Hey Platzi 😎!
        </h1>
        <div className="m-2">
          <button
            onClick={addNewFox}
            className="w-40 p-3 mr-2 bg-blue-600 shadow-lg dark:text-white rounded-3xl"
          >
            Add new Fox
          </button>
          <button
            onClick={deleteFox}
            className="w-40 p-3 text-black bg-red-600 shadow-lg dark:text-white rounded-3xl "
          >
            Delete new Fox
          </button>
        </div>

        {images.map(({ id, url }) => {
          return (
            <div key={id} className="p-4">
              <LazyImage
                alt={url}
                src={url}
                width={320}
                height="auto"
                title="Random fox"
                className="bg-gray-400 rounded-3xl"
              />
            </div>
          );
        })}
      </main>

      <footer></footer>
    </>
  );
};

export default Home;
